[stdlib]
minimum_version = "0.0.15"

[tasks.shell]
interactive = true
packages = ["base", "bash", "claude-code", "claude-code-minimal-plugin", "curl"]
exec = "bash --noprofile -l"

[tasks.claude]
interactive = true
packages = ["base", "bash", "claude-code", "claude-code-minimal-plugin", "curl"]
exec = "claude --dangerously-skip-permissions"

[tasks.opencode]
interactive = true
packages = ["base", "bash", "opencode", "curl"]
exec = "opencode"

[session]
packages = ["chafa", "term.everything", "base", "toolchain", "make", "meson", "ninja", "pkgconf", "expat", "libffi", "libxml2", "zlib", "xorgproto", "libx11", "font-util", "xtrans", "freetype", "mesa", "python", "libfontenc", "libxkbfile", "gettext", "perl", "wayland", "wayland-protocols", "libepoxy", "libxcvt", "libxfont2", "xkbcomp", "xkeyboard-config", "dbus", "nettle", "pixman", "libdrm", "xwayland", "niri"]
